debug: true

max-batch-size: 10

# Database configuration settings
# Supported types: SQLITE, MARIADB, MYSQL
database:
  type: SQLITE
  table-prefix: app_
  # host: localhost
  # port: 5432
  # database: mydatabase
  # user: user
  # password: password
